# Change these first
owner: NiedbalskiPatryk # Your GitHub organization or username, where this repository lives
repo: teststrapiUpptime # The name of this repository

sites:
  - name: test
    url: https://benefique-livre-79448.herokuapp.com/

status-website:
  baseUrl: /teststrapiUpptime
  name: teststrapiUpptime
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
